export enum ENatipayJwtTokenType {
  SIGNIN = 'SIGNIN',
  SIGNUP = 'SIGNUP',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  CHECKIN = 'CHECKIN',
  CHECKOUT = 'CHECKOUT',
  DEVICE = 'DEVICE',
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  SIGNOUT = 'SIGNOUT',
  IOT = 'IOT',
  DEVELOPER_APP = 'DEVELOPER_APP',
}
