export enum EAccountHolderType {
  PESSOA_FISICA = 'PESSOA_FISICA',
  PESSOA_JURIDICA = 'PESSOA_JURIDICA',
  CONTA_CONJUNTA = 'CONTA_CONJUNTA',
  CONTA_EMPRESARIAL = 'CONTA_EMPRESARIAL',
  CONTA_INVESTIMENTO = 'CONTA_INVESTIMENTO',
}
