export enum NatipayMemberRulesEnum {
  ADMIN = 'ADMIN',
  USER = 'USER',
  OWNER = 'OWNER',
  SUPPORT = 'SUPPORT',
  PARTNER = 'PARTNER',
  FINANCE = 'FINANCE',
  MARKETING = 'MARKETING',
  SALES = 'SALES',
  MENAGER = 'MENAGER',
  DEVELOPER = 'DEVELOPER',
}
