export enum ETransactionCategory {
  // Income
  SALARY = 'SALARY',
  INVESTMENT_INCOME = 'INVESTMENT_INCOME',
  REFUND = 'REFUND',
  TRANSFER_IN = 'TRANSFER_IN',
  PIX_IN = 'PIX_IN',

  // Expenses
  FOOD = 'FOOD',
  TRANSPORT = 'TRANSPORT',
  SHOPPING = 'SHOPPING',
  ENTERTAINMENT = 'ENTERTAINMENT',
  HEALTH = 'HEALTH',
  EDUCATION = 'EDUCATION',
  BILLS = 'BILLS',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  TRAVEL = 'TRAVEL',
  FUEL = 'FUEL',

  // Banking
  TRANSFER_OUT = 'TRANSFER_OUT',
  PIX_OUT = 'PIX_OUT',
  WITHDRAWAL = 'WITHDRAWAL',
  DEPOSIT = 'DEPOSIT',
  FEES = 'FEES',

  // Investment
  INVESTMENT = 'INVESTMENT',
  INVESTMENT_SALE = 'INVESTMENT_SALE',

  // Other
  OTHER = 'OTHER',
  UNCATEGORIZED = 'UNCATEGORIZED',
}
