export enum ETransactionType {
  // PIX
  PIX_SENT = 'PIX_SENT',
  PIX_RECEIVED = 'PIX_RECEIVED',
  PIX_RETURNED = 'PIX_RETURNED',

  // Transfers
  TRANSFER_SENT = 'TRANSFER_SENT',
  TRANSFER_RECEIVED = 'TRANSFER_RECEIVED',
  TED_SENT = 'TED_SENT',
  TED_RECEIVED = 'TED_RECEIVED',
  DOC_SENT = 'DOC_SENT',
  DOC_RECEIVED = 'DOC_RECEIVED',

  // Card Transactions
  CARD_PURCHASE = 'CARD_PURCHASE',
  CARD_WITHDRAWAL = 'CARD_WITHDRAWAL',
  CARD_PAYMENT = 'CARD_PAYMENT',
  CARD_REFUND = 'CARD_REFUND',

  // Deposits & Withdrawals
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  ATM_WITHDRAWAL = 'ATM_WITHDRAWAL',

  // Fees & Charges
  FEE = 'FEE',
  MAINTENANCE_FEE = 'MAINTENANCE_FEE',
  OVERDRAFT_FEE = 'OVERDRAFT_FEE',
  INTEREST = 'INTEREST',

  // Investment
  INVESTMENT_PURCHASE = 'INVESTMENT_PURCHASE',
  INVESTMENT_SALE = 'INVESTMENT_SALE',
  INVESTMENT_INCOME = 'INVESTMENT_INCOME',

  // System
  SYSTEM_ADJUSTMENT = 'SYSTEM_ADJUSTMENT',
  BALANCE_CORRECTION = 'BALANCE_CORRECTION',
}
