export enum ETransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REVERSED = 'REVERSED',
  DISPUTED = 'DISPUTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  SCHEDULED = 'SCHEDULED',
  EXPIRED = 'EXPIRED'
} 