export enum PayioUserTypeEnum {
  NONE = 'NONE',
  USER = 'USER',
  PARTNER = 'PARTNER',
  ADMIN = 'ADMIN',
  CLIENT = 'CLIENT',
  CUSTOMER = 'CUSTOMER',
  DEVELOPER = 'DEVELOPER',
  TESTER = 'TESTER',
  DISTRIBUTOR = 'DISTRIBUTOR',
  SUPER_ADMIN = 'SUPER_ADMIN',
}
