export enum EAuthType {
  PASSWORD = 'PASSWORD',
  BIOMETRIC = 'BIOMETRIC',
  FINGERPRINT = 'FINGERPRINT',
  FACE_ID = 'FACE_ID',
  PIN = 'PIN',
  OTP = 'OTP',
  HARDWARE_TOKEN = 'HARDWARE_TOKEN',
  SMS_CODE = 'SMS_CODE',
  EMAIL_CODE = 'EMAIL_CODE'
} 