/* eslint-disable @typescript-eslint/naming-convention */
export enum ENatipaySaleChannel {
  PAYIO_CASH = 'PAYIOCASH',
  PAYIO_CHEF = 'PAYIOCHEF',
  GESTOR_FINANCE = 'GESTOR-FINANCE',
  NATIPAY = 'NATIPAY',
  NATIPAY_TAB = 'NATIPAY-TAB',
  NATI_PDV = 'NATI-PDV',
  NATI_SMART_POS = 'NATI-SMART-POS',
  NATI_TOTEM = 'NATI-TOTEM',
  MOBYO_DELIVERY = 'MOBYO-DELIVERY',
  MOBYO_TAB = 'MOBYO-TAB',
  MOBYO_PDV = 'MOBYO-PDV',
  MOBYO_SMART_POS = 'MOBYO-SMART-POS',
  MOBYO_TOTEM = 'MOBYO-TOTEM',
  DEFAULT = 'DEFAULT',
}
