/* eslint-disable @typescript-eslint/naming-convention */
export enum ENatipaySaleChannel {
  PAYIO_CASH = 'PAYIOCASH',
  PAYIO_CHEF = 'PAYIOCHEF',
  PAYIO_SMART = 'PAYIOSMART',
  PAYIO_BIGCHEF = 'PAYIOBIGCHEF',
  PAYIO_GESTOR = 'PAYIO-GESTOR',
  PAYIO_GESTOR_ORDER = 'PAYIO-GESTOR-ORDER',
  PAYIO_GESTOR_CREDIT = 'PAYIO-GESTOR-CREDIT',
  GESTOR_FINANCE = 'GESTOR-FINANCE',
  NATIPAY = 'NATIPAY',
  NATIPAY_TAB = 'NATIPAY-TAB',
  NATI_PDV = 'NATI-PDV',
  NATI_DELIVERY = 'NATI-DELIVERY',
  NATI_SMART_POS = 'NATI-SMART-POS',
  NATI_TOTEM = 'NATI-TOTEM',
  MOBYO_DELIVERY = 'MOBYO-DELIVERY',
  DEFAULT = 'DEFAULT',
}
