export enum EAccountType {
  CORRENTE = 'CORRENTE',
  POUPANCA = 'POUPANCA',
  SALARIO = 'SALARIO',
  INVESTIMENTO = 'INVESTIMENTO',
  EMPRESARIAL = 'EMPRESARIAL',
  CONJUNTA = 'CONJUNTA',
  UNIVERSITARIA = 'UNIVERSITARIA',
  DIGITAL = 'DIGITAL',
}
