export enum EAccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
  PENDING_ACTIVATION = 'PENDING_ACTIVATION',
  UNDER_REVIEW = 'UNDER_REVIEW',
}
