export enum EWebhookType {
  PING = 'PING',
  GET_PRODUCT = 'GET_PRODUCT',
  SEND_ORDER = 'SEND_ORDER',
  GET_ORDER = 'GET_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
  GET_ORDER_STATUS = 'GET_ORDER_STATUS',
  VISION_SEND_IMG = 'VISION_SEND_IMG',
  VISION_ASSIGN_POSITION = 'VISION_ASSIGN_POSITION',
  VISION_UNASSIGN_POSITION = 'VISION_UNASSIGN_POSITION',
  VISION_GET_POSITION = 'VISION_GET_POSITION',
  NFCE_GET_XML = 'NFCE_GET_XML',
  GET_TAB = 'GET_TAB',
}
