export enum EWebhookType {
  PING = 'PING',
  GET_PRODUCT = 'GET_PRODUCT',
  SEND_ORDER = 'SEND_ORDER',
  GET_ORDER = 'GET_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
  GET_ORDER_STATUS = 'GET_ORDER_STATUS',
  NFCE_GET_XML = 'NFCE_GET_XML',
  GET_TAB = 'GET_TAB',
  VISION = 'VISION',
}
